src/app/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path

from app.conf.environ import env

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("tree_menu.urls")),
]

if env("DEBUG", cast=bool, default=False):
    import debug_toolbar

    urlpatterns.append(path("__debug__/", include(debug_toolbar.urls)))

src/tree_menu/urls.py
from django.urls import path

from tree_menu.views import IndexPageView
from tree_menu.views import slug_view

app_name = "menu"

urlpatterns = [
    path(f"{app_name}/", IndexPageView.as_view(), name="index"),
    path(f"{app_name}/<slug:item_slug>/", slug_view, name="index-detail"),
]

src/tree_menu/models.py
from django.db import models

from tree_menu import urls as menu_urls


class Menu(models.Model):
    title = models.CharField(max_length=255, unique=True, verbose_name="Menu title")
    slug = models.SlugField(max_length=255, verbose_name="Menu slug")

    class Meta:
        verbose_name = "Menu"
        verbose_name_plural = "Menus"

    def __str__(self):
        return self.title


class Item(models.Model):
    title = models.CharField(max_length=255, verbose_name="Item title")
    slug = models.SlugField(max_length=255, verbose_name="Item slug", unique=True, db_index=True)
    menu = models.ForeignKey(Menu, blank=True, related_name="items", on_delete=models.CASCADE)
    parent = models.ForeignKey("self", blank=True, null=True, related_name="children", on_delete=models.CASCADE)
    url = models.URLField(max_length=300, editable=False, blank=True)

    class Meta:
        verbose_name = "Menu item"
        verbose_name_plural = "Menu items"

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.pk:
            super().save(*args, **kwargs)
        self.url = f"/{menu_urls.app_name}/?&{str(self.menu)}={self.pk}"
        super().save(*args, **kwargs)

src/tree_menu/views.py
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.views.generic import TemplateView

from tree_menu import models


class IndexPageView(TemplateView):
    template_name = "index.html"


def slug_view(request, item_slug):
    menu_item = get_object_or_404(models.Item, slug=item_slug)
    return redirect(menu_item.url)

src/app/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    {% block content %}{% endblock %}
</body>
</html>

src/tree_menu/templates/index.html
{% extends 'base.html' %}

{% block title %} Tree Menu {% endblock %}

{% load draw_menu %}
{% block content %}

{% draw_menu 'main_menu' %}
<br>
<a href="{% url 'menu:index-detail' 'comment_4' %}">PRESS ME I'M COMMENT 4</a>
<br>
<a href="{% url 'menu:index-detail' 'comment_8' %}">AND ME I'M COMMENT 8</a>

{% draw_menu 'secondary_menu' %}
<br>
<a href="{% url 'menu:index-detail' 'comment_19' %}">ME, ME I'M COMMENT 19</a>
{% endblock %}

src/tree_menu/templates/nested_menu.html
<ul>
    {% for item in items %}
        <li>
            <a href="?{{ other_querystring }}&{{ menu }}={{ item.id }}">{{ item.title }}</a>
        </li>

        {% if item.child_items %}
            {% include 'nested_menu.html' with items=item.child_items %}
        {% endif %}

    {% endfor %}
</ul>